### ISSUE TITLE
Users will be able to see news posts

### ISSUE THREAD

**Issue by iambriansreed** [RevolutionVA/Website#7]

**Comment by iambriansreed** [comment]
Do we want to have a news area on the site? @erikpmp @1kevgriff @lynnaloo?

**Comment by erikpmp** [comment]
Later...closer to the conf maybe

**Comment by erikpmp** [comment]
It's time for this.

**Comment by iambriansreed** [comment]
@erikpmp you all haven't posted any news yet is this still a need to do?

**Comment by erikpmp** [comment]
It's not necessary. But if it was there, I think we would use it. Certainly for posting pics of the 2016 conf and leading into the 2017 conf it would be good. Maybe table it until we start talking about 2017...you've done enough already (and it's appreciated).
